baseURL = "https://relationship-anarchy.org"
title = "relationship-anarchy.org"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "relationship-anarchy"
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "de"

[params.info]
description = "von Liebe ohne Konventionen"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Mr. Smith"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false
rtl = false

[params.sidebar]
enable = false

[params.widgets]
#header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = "MunifTanjim"
email = "mr.smith@relationship-anarchy.org"
#facebook = "MunifTanjim"
github = "relationship-anarchy"
#gitlab = "MunifTanjim"
#instagram = "MunifTanjim"
#linkedin = "muniftanjim"
#twitter = "MunifTanjim"
#telegram = "MunifTanjim"
#google_scholar = "qc6CJjYAAAAJ"
#youtube = "UCT-U0rNerYxItGcuoPX-WYA"

[params.comments]
enable = true

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "MunifTanjim"
repository = "minimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

#[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/relationship-anarchy/relationship-anarchy.org"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.de]
lang = "de"
languageName = "Deutsch"
weight = 1
[languages.en]
lang = "en"
languageName = "English"
weight = 2
