baseURL = "https://relationship-anarchy.org"
title = "relationship-anarchy.org"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "relationship-anarchy"
googleAnalytics = "UA-102169098-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "de"

[params.info]
description = "von Liebe ohne Konventionen"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Mr. Smith"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "MunifTanjim"
email = "mr.smith@relationship-anarchy.org"
facebook = "MunifTanjim"
github = "relationship-anarchy"
instagram = "MunifTanjim"
linkedin = "muniftanjim"
twitter = "MunifTanjim"
telegram = "MunifTanjim"

[params.social.config]
#platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin","telegram"]
platforms = ["github","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

#[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/relationship-anarchy/relationship-anarchy.org"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.de]
lang = "de"
languageName = "Deutsch"
weight = 1
[languages.en]
lang = "en"
languageName = "English"
weight = 2
